/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_test2_Test2 */

#ifndef _Included_test_test2_Test2
#define _Included_test_test2_Test2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_test2_Test2
 * Method:    avg
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_test_test2_Test2_avg
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
