/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_TestDynamic */

#ifndef _Included_test_TestDynamic
#define _Included_test_TestDynamic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_TestDynamic
 * Method:    multiply
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_test_TestDynamic_multiply
  (JNIEnv *, jclass, jdouble, jdouble);

JNIEXPORT jdouble JNICALL Java_test_TestDynamic_sum__DD
  (JNIEnv *, jclass, jdouble, jdouble);

JNIEXPORT jdouble JNICALL Java_test_TestDynamic_sum__DDD
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

JNIEXPORT jdouble JNICALL Java_test_TestDynamic_divide
  (JNIEnv *, jclass, jdouble, jdouble);    

JNIEXPORT jstring JNICALL Java_test_TestDynamic_speak
  (JNIEnv *, jclass);      

JNIEXPORT jboolean JNICALL Java_test_TestDynamic_reverse__Z
  (JNIEnv *, jclass, jboolean);      

JNIEXPORT jboolean JNICALL Java_test_TestDynamic_reverse__ZZ
  (JNIEnv *, jclass, jboolean, jboolean); 

JNIEXPORT jdoubleArray JNICALL Java_test_TestDynamic_doubleArray
  (JNIEnv *, jclass);      

#ifdef __cplusplus
}
#endif
#endif
